name: instacart-recs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyspark=3.5.0
  - pandas=2.1.4
  - numpy=1.26.2
  - pyarrow=14.0.1
  - jupyter=1.0.0
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - pytest=7.4.3
  - black=23.12.1
  - flake8=7.0.0
  - pip
  - pip:
      - pyyaml==6.0.1
      - python-dotenv==1.0.0
      - tqdm==4.66.1
      - plotly==5.18.0
      - pytest-cov==4.1.0
      - pre-commit==3.6.0
      - openpyxl==3.1.2
